### ISSUE TITLE
Flink's application at Didi

### ISSUE THREAD

**Issue by fancycrabtree** [flink-china/articles#2]
滴滴实时计算负责人薛康老师的分享，他们 Flink SQL 的应用比例极其高，有对 SQL 这块感兴趣的小伙伴可以重点关注，大厂一线生产环境的应用经验分享呀，并且薛老师正在招人哦，想整理这期或者投简历的同学请留言！

直播回看：
https://ververica.cn/developers/flink-forward-virtual-conference/

**Comment by LadyForest** [comment]
Hi @fancycrabtree would you mind assigning it to me :D
