### ISSUE TITLE
网易云音乐实时数仓实践

### ISSUE THREAD

**Issue by fancycrabtree** [flink-china/articles#5]
作者：汪磊  |  网易 数据平台开发专家

1. 云音乐整体数据平台架构介绍
2. 云音乐 Flink 实时数仓和元数据中心整合
3. 目前面临的问题和挑战
4. 批流一体的实践和规划

**Comment by showMeuDream** [comment]
整理

**Comment by fancycrabtree** [comment]
DL:6.22
